Set -std=gnu99 for gcc on all architectures
Previously the cmake file only sets `-std=gnu99` when it is on x86(-64),
which causes compilation failure on other architectures when gcc is
used.

GCC currently defaults to `-std=gnu23`, which would fail the build with:

    blosc/shuffle.c:26:15: error: ‘bool’ cannot be defined via ‘typedef’

This patch fixes it by setting `-std=gnu99` for gcc on all
architectures.